version: "3.9"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: "http://localhost:8000" 
    container_name: frontend
    ports:
      - 3000:80
      - 443:443
    env_file:
      - ./client/.env

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
